# BLE básico
CONFIG_ZMK_BLE=y

# USB
CONFIG_ZMK_USB_LOGGING=n

# Energia
CONFIG_ZMK_SLEEP=y

# 5 min até dormir 
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# reduz atividade após 30s parado
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Bateria 
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
